package dam;
// Generated 11-nov-2020 11:58:04 by Hibernate Tools 3.6.0



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private Categorias categorias;
     private String nombreProducto;
     private Float precio;

    public Productos() {
    }

    public Productos(Categorias categorias, String nombreProducto, Float precio) {
       this.categorias = categorias;
       this.nombreProducto = nombreProducto;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


